services:
  postgres:
    image: postgres:latest
    networks:
      - terrorism_network
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: shalom
      POSTGRES_PASSWORD: password
      POSTGRES_DB: terrorism_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      
  neo4j:
    image: neo4j:latest
    networks:
      - terrorism_network
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: neo4j/password
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

networks:
  terrorism_network:
    driver: bridge

volumes:
  postgres_data:
  neo4j_data:
  neo4j_logs: